spring:
  r2dbc:
    url: r2dbc:h2:mem:///db;DB_CLOSE_DELAY=-1;
    username: 'sa'
    password: 'pass'
#  datasource:
#    url: 'jdbc:h2:mem:db'
#    driverClassName: org.h2.Driver
#    username: 'sa'
#    password: 'pass'
management:
  endpoints:
    web:
      exposure.include: info, health